### ISSUE TITLE
代码质量这么差，干嘛还要加到paperwithcode里

### ISSUE THREAD

**Issue by acdart** [DavidChenTaipei/BANet#1]
is it a bug?
https://github.com/DavidChenTaipei/BANet/blob/72788962df7e0f9e92620e83ce0bad0fb84ab683/lib/models/banet.py#L131

is it a bug?
https://github.com/DavidChenTaipei/BANet/blob/72788962df7e0f9e92620e83ce0bad0fb84ab683/lib/models/banet.py#L147

代码质量这么差，干嘛还要加到paperwithcode里

**Comment by DavidChenTaipei** [comment]
@acdart 
This is the only BANet implement in Github, if you like it, use it. If you don't, write it by yourself.

**Comment by acdart** [comment]
at least, you should test your code before make it public in papaerwithcode
